### ISSUE TITLE
can not run the example

### ISSUE THREAD

**Issue by pfliu-nlp** [ExpressAI/omneval#18]
when I run this example, I got:
```shell
omneval "sst2" --arch "roberta-large"
```

```

Traceback (most recent call last):
  File "/usr0/home/pliu3/anaconda3/bin/omneval", line 33, in <module>
    sys.exit(load_entry_point('omneval', 'console_scripts', 'omneval')())
  File "/usr0/home/pliu3/anaconda3/bin/omneval", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr0/home/pliu3/anaconda3/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr0/home/pliu3/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'omneval.main'
```

**Comment by vincent1rookie** [comment]
fixed
